version: '2'

services:
  haproxy:
    image: haproxy:2.1.4
    ports:
      - 3306:3306
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    image: mysql:5.7
